module.exports = {
    ROLE_SUPER_ADMIN : "SUPER ADMIN",
    ROLE_ADMIN : "ADMIN",
    ROLE_USER : "USER",

    LEAD_META_KEY_NOTES :"NOTES",
    LEAD_META_KEY_OFFERS_DEALS :"OFFER_DEALS",

    LOGIN_TYPE_BASIC : "BASIC",
    LOGIN_TYPE_SOCIAL_APP : "SOCIAL_APP",
    LOGIN_TYPE_BOTH : "BOTH",
}
